version: '2'
services:
  jwt-auth:
    volumes:
      - ".:/app:rw"
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    command: mongod
    image: mongo:latest
    ports:
      - "27100:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none